# Generated by Django 3.0.3 on 2021-03-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_email', models.CharField(help_text='write your email', max_length=50, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=30)),
                ('stu_dob', models.DateTimeField()),
                ('stu_gender', models.CharField(max_length=10)),
                ('stu_sem', models.IntegerField()),
                ('stu_address', models.CharField(help_text='write your add', max_length=100)),
                ('stu_city', models.CharField(max_length=20)),
                ('stu_state', models.CharField(max_length=20)),
                ('stu_zip', models.CharField(max_length=6)),
                ('stu_mobile_no', models.CharField(max_length=10)),
                ('stu_image', models.ImageField(blank=True, upload_to='stu_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teach_email', models.CharField(help_text='write your email', max_length=50, primary_key=True, serialize=False)),
                ('teach_name', models.CharField(max_length=30)),
                ('teach_dob', models.DateTimeField()),
                ('teach_gender', models.CharField(max_length=10)),
                ('teach_address', models.CharField(help_text='write your add', max_length=100)),
                ('teach_city', models.CharField(max_length=20)),
                ('teach_state', models.CharField(max_length=20)),
                ('teach_zip', models.CharField(max_length=6)),
                ('teach_mobile_no', models.CharField(max_length=10)),
                ('teach_image', models.ImageField(blank=True, upload_to='teacher_pics')),
            ],
        ),
    ]
