# Generated by Django 3.0.3 on 2021-03-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_created',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_due_date',
            field=models.DateTimeField(default=None),
        ),
    ]
