# Generated by Django 3.0.3 on 2021-03-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_student'),
        ('teacher', '0003_auto_20210317_1732'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_file', models.FileField(null=True, upload_to='submissions/')),
                ('submission_assignment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='teacher.Assignment')),
                ('submission_student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='submission_student', to='login.Student')),
            ],
        ),
    ]
