# Generated by Django 3.0.3 on 2021-03-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210321_0039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
