# Generated by Django 3.0.3 on 2021-03-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210321_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_added_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_marks',
            field=models.FloatField(default=None),
        ),
    ]
