# Generated by Django 3.0.3 on 2021-03-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210321_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_marks',
            field=models.FloatField(default=None, null=True),
        ),
    ]
